const IdGenerator = require('../../utils/idGenerator')
const {handleErrors} = require('../../handlers/errorHandlers')


/**
 * this method creates a learner record with these attributes:
 * admNo: generated by generateLearnerId function from IdGenerator
 * names:first and last name
 * yob
 * gender
 *classroom
 * disability
 * medical condition
 * UPI/ NEMIS number
 * birth certificate number
 * admittedBy: staff who admitted the learner
 * parents details: (names, id, contact information, address)
 * **/


const admitLearner = async (model,req,res) => {
  try {
      const idGenerator = new IdGenerator()
      const studentData={
          ...req.body,
          admNo:idGenerator.generateLearnerId()
      }
      const result = await new model(studentData).save()

      if (!result){
          return res.status(500).json({
              success:false,
              message:"Failed to Admit Learner"
          })
      }

      return res.status(200).json({
          success: true,
          result,
          message: 'Successfully Created the document in Model ',
      });


  }catch (error) {
      console.log(error)
      if (error.code===11000){
          let errorMessage="";
          if (error.keyPattern.admNo){
              errorMessage="Student Id already exist"
          }else if (error.keyPattern.UPINo){
              errorMessage="Student NEMIS already exist"
          }else if (error.keyPattern.birthCertificateNo){
              errorMessage="Student Birth Certificate Number already exist"
          }

          return res.status(400).json({
              success:false,
              message:errorMessage,
              error:error.message
          })
      }
      handleErrors(res,error)
  }
}

module.exports = {admitLearner}
